/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormVeTau.java
 *
 * Created on Aug 27, 2011, 1:32:48 AM
 */
package View;

import Model.ChuyenDi;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Owner
 */
public class FormTimChuyenDi extends javax.swing.JFrame {
    
    Vector data;
    DefaultTableModel model;

    /**
     * Creates new form FormVeTau
     */
    public FormTimChuyenDi() {
        initComponents();
        DangKy.setEnabled(false);
        this.getContentPane().setBackground(new Color(204, 204, 255));
    }
    
    class MyDefaultTableModel extends DefaultTableModel {        

        public MyDefaultTableModel(Object[] columnNames, int rowCount) {            
            super(columnNames, rowCount);            
        }        

        @Override
        public boolean isCellEditable(int row, int col) {            
            return false;            
        }        
    }    
    
    public void hienthiketqua(ChuyenDi[] cd) {
        int i = 0;
        Vector Row[] = new Vector[1000];
        String s[] = {"NgayXP", "DiemXP", "DiemDen", "GioXP", "GiaVe"};
        model = new MyDefaultTableModel(s, 0);
        jTable1.setModel(model);
        data = new Vector();
        try {
            
            for (i = 0; i < cd.length; i++) {
                Row[i] = new Vector();
                Row[i].add(cd[i].getNgayXP());
                Row[i].add(cd[i].getDiemXP());
                Row[i].add(cd[i].getDiemDen());
                Row[i].add(cd[i].getGioXP());
                Row[i].add(cd[i].getGiaVe());
                model.addRow(Row[i]);
                data.add(Row[i]);
            }
            
        } catch (Exception e) {
            if (cd == null) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy  !");
            }
            
        }
    }
    
    public String getDiemXP() {
        return (String) CBDiemXP.getSelectedItem();
    }
    
    public String getDiemDen() {
        return (String) CBDiemDen.getSelectedItem();
    }
    
    public String getNgayXP() {
        return NgayXP.getText();
    }
    
    public Vector getData() {
        return data;
    }
    
    public int getSelectIndex() {
        return jTable1.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBDiemXP = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        CBDiemDen = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        TimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        NgayXP = new javax.swing.JTextField();
        DangKy = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TÌM KIẾM CHUYẾN ĐI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Điểm XP");

        CBDiemXP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hà Nội", "Hà Nam", "Nam Định", "Ninh Bình", "Thanh Hóa", "Nghệ An", "Hà Tĩnh", "Quảng Bình", "Quảng Trị", "Thừa Thiên Huế", "Đà Nẵng", "Quảng Nam", "Quảng Ngãi", "Bình Định", "Phú Yên", "Khánh Hòa", "Ninh Thuận", "Bình Thuận", "Đồng Nai", "Bình Dương", "TP Hồ Chí Minh" }));
        CBDiemXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDiemXPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Điểm đến");

        CBDiemDen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hà Nội", "Hà Nam", "Nam Định", "Ninh Bình", "Thanh Hóa", "Nghệ An", "Hà Tĩnh", "Quảng Bình", "Quảng Trị", "Thừa Thiên Huế", "Đà Nẵng", "Quảng Nam", "Quảng Ngãi", "Bình Định", "Phú Yên", "Khánh Hòa", "Ninh Thuận", "Bình Thuận", "Đồng Nai", "Bình Dương", "TP Hồ Chí Minh" }));
        CBDiemDen.setSelectedIndex(20);
        CBDiemDen.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ngày đi");

        TimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TimKiem.setText("Tìm kiếm");
        TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày XP", "Điểm XP", "Điểm đến", "Giờ đi", "Giá vé"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        DangKy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DangKy.setText("Đăng Ký");
        DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangKyActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\hong\\Desktop\\images (1).jpg")); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TimKiem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NgayXP)
                            .addComponent(CBDiemXP, 0, 161, Short.MAX_VALUE)
                            .addComponent(CBDiemDen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DangKy)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBDiemXP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBDiemDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NgayXP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimKiem)
                    .addComponent(DangKy))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangKyActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DangKyActionPerformed
    
private void TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemActionPerformed
// TODO add your handling code here:

}//GEN-LAST:event_TimKiemActionPerformed
    
private void CBDiemXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDiemXPActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CBDiemXPActionPerformed
    
//Đăng ký sự kiện

    public void timKiemActionPerform(ActionListener evt) {
        TimKiem.addActionListener(evt);
    }
    
    public void dangkyActionPerform(ActionListener al) {
        DangKy.addActionListener(al);
    }
    
    public void clickTableActionPerform(MouseListener ml) {
        jTable1.addMouseListener(ml);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBDiemDen;
    private javax.swing.JComboBox CBDiemXP;
    public javax.swing.JButton DangKy;
    private javax.swing.JTextField NgayXP;
    public javax.swing.JButton TimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
